[package]
name    = "startinpy"
version = "0.7.1"
authors = ["Hugo Ledoux <h.ledoux@tudelft.nl>"]
license = "MIT"
homepage="https://github.com/hugoledoux/startinpy"
repository="https://github.com/hugoledoux/startinpy"
description = "A Delaunay triangulator for terrains"
readme = "README.md"
edition = "2018"


[dependencies]
startin = "0.5.0"
# startin = { path = "../startin" }
las = { version = "0.7.4", features = ["laz"] }


[dependencies.pyo3]
version = "0.11"
features = ["extension-module"]


[lib]
name = "startinpy"
crate-type = ["cdylib"]


[package.metadata.maturin]
requires-python = ">=3.6"
requires-dist = ["toml==0.10.0"]
classifier=["License :: OSI Approved :: MIT License"]