[package]
name    = "startin"
version = "0.6.2"
authors = ["Hugo Ledoux <h.ledoux@tudelft.nl>"]
license = "MIT"
homepage="https://github.com/hugoledoux/startin_python"
repository="https://github.com/hugoledoux/startin_python"
description = "A Delaunay triangulator for terrains"
readme = "README.md"
edition = "2018"


[dependencies]
startin = "0.4.7"
las = { version = "0.7.1", features = ["laz"] }


[dependencies.pyo3]
version = "0.11"
features = ["extension-module"]


[lib]
name = "startin"
crate-type = ["cdylib"]


[package.metadata.maturin]
requires-python = ">=3.6"
requires-dist = ["toml==0.10.0"]
classifier=["License :: OSI Approved :: MIT License"]